config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :friend_recs
  #get 'home/index'
  get 'home/about'
  root 'friend_recs#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend_rec.rb
class FriendRec < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friend_recs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friend_recs_controller.rb
class FriendRecsController < ApplicationController
  before_action :set_friend_rec, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:index, :show]
  before_action :correct_user,only: [:edit,:update,:destroy]
  # GET /friend_recs or /friend_recs.json
  def index
    @friend_recs = FriendRec.all
  end

  # GET /friend_recs/1 or /friend_recs/1.json
  def show
  end

  # GET /friend_recs/new
  def new
    @friend_rec = current_user.friend_recs.build
  end

  # GET /friend_recs/1/edit
  def edit
  end

  # POST /friend_recs or /friend_recs.json
  def create
    #@friend_rec = FriendRec.new(friend_rec_params)
    @friend_rec = current_user.friend_recs.build(friend_rec_params)
    respond_to do |format|
      if @friend_rec.save
        format.html { redirect_to friend_rec_url(@friend_rec), notice: "Friend rec was successfully created." }
        format.json { render :show, status: :created, location: @friend_rec }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_recs/1 or /friend_recs/1.json
  def update
    respond_to do |format|
      if @friend_rec.update(friend_rec_params)
        format.html { redirect_to friend_rec_url(@friend_rec), notice: "Friend rec was successfully updated." }
        format.json { render :show, status: :ok, location: @friend_rec }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_recs/1 or /friend_recs/1.json
  def destroy
    @friend_rec.destroy

    respond_to do |format|
      format.html { redirect_to friend_recs_url, notice: "Friend rec was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @friend_rec = current_user.friend_recs.find_by(id: params[:id])
    redirect_to friend_recs_path,notice:"Not Authorized To Edit This Friend" if @friend_rec.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_rec
      @friend_rec = FriendRec.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_rec_params
      params.require(:friend_rec).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_recs_helper.rb
module FriendRecsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friend_recs/_form.html.erb
<%= form_with(model: friend_rec) do |form| %>
  <% if friend_rec.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend_rec.errors.count, "error") %> prohibited this friend_rec from being saved:</h2>

      <ul>
        <% friend_rec.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="field form-group">
    <%= form.text_field :first_name,class:"form-control",placeholder:"First Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :last_name,class:"form-control",placeholder:"Last Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :email,class:"form-control",placeholder:"Email" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.text_field :phone,class:"form-control",placeholder:"Phone Number" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.text_field :twitter,class:"form-control",placeholder:"Twitter" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.number_field :user_id,id: :friend_user_id,class:"form-control",value:current_user.id ,type: :hidden%>
  </div>
<br>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/friend_recs/_friend_rec.html.erb
<div id="<%= dom_id friend_rec %>">
  <p>
    <strong>First name:</strong>
    <%= friend_rec.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend_rec.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend_rec.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend_rec.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend_rec.twitter %>
  </p>

</div>

app/views/friend_recs/edit.html.erb
<div class="card">
  <div class="card-header text-center">
    <h1>Editing friend</h1>
  </div>
  <div class="card-body">
    <%= render "form", friend_rec: @friend_rec %>
  </div>
  <div class="card-footer text-muted text-center">
    <%= link_to "Show", @friend_rec,class:"btn btn-secondary" %>
    <br><br>
    <%= link_to "Back", friend_recs_path,class:"btn btn-dark" %>
    <br><br>
    <%= button_to "Destroy", @friend_rec, method: :delete , data: {confirm:'Are you sure?'} ,class:"btn btn-danger"%></td>
  </div>
</div>

app/views/friend_recs/index.html.erb
<% if user_signed_in?%>
  <h1>Friend recs</h1>
  <div id="friend_recs">
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead table-success">
        <tr>
          <th> Name </th>
          <th> Email </th>
          <th> Phone </th>
          <th> Twitter </th>
          <th  colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @friend_recs.each do |friend_rec| %>
          <% if friend_rec.user == current_user%>
            <tr>
              <td><%= link_to friend_rec.first_name + " " + friend_rec.last_name, friend_rec ,class:"link-success"%></td>

              <td><%= friend_rec.email %></td>
          
              <td><%= friend_rec.phone %></td>
          
              <td><%= friend_rec.twitter %></td>
            
              <td><%= button_to "Destroy", friend_rec, method: :delete , data: {confirm:'Are you sure?'} ,class:"btn btn-outline-danger btn-sm"%></td>
            </tr>
          <% end%>
        <% end%>
      </tbody>
    </table>
  </div>

  <%= link_to "New friend", new_friend_rec_path,class:"btn btn-secondary"%>
<% else %>
  <h1>Welcome to Friends App</h1> 
<% end%>

app/views/friend_recs/new.html.erb
<div class="card text-center w-50">
  <div class="card-header">
    <h2>Add New Friend </h2>
  </div>
  <div class="card-body">
    <%= render "form", friend_rec: @friend_rec %>  
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Back", friend_recs_path ,class:"btn btn-dark"%>
  </div>
</div>

app/views/friend_recs/show.html.erb
<div class="card text-center border-success w-50">
  <div class="card-header">
    <h2><%= @friend_rec.first_name %>
    <%= @friend_rec.last_name %></h2>
  </div>
  <div class="card-body">
    <ul class="field">
      <li class="field form-group form-control"><%= @friend_rec.email %></li><br>
      <li class="field form-group form-control"><%= @friend_rec.phone %></li><br>
      <li class="filed form-group form-control"><%= @friend_rec.twitter %></li><br>
    </ul>
  </div>
  <div class="card-footer">
    <%= link_to "Edit", edit_friend_rec_path(@friend_rec),class:"btn btn-secondary" %>
    <br><br>
    <%= link_to "Back", friend_recs_path ,class:"btn btn-dark"%> 
    <br><br>  
    <%= button_to "Destroy", @friend_rec, method: :delete , data: {confirm:'Are you sure?'} ,class:"btn btn-danger"%>
  </div>
</div>

app/views/home/_footer.html.erb
<h6></h6>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <%= link_to 'Friends App' ,root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About us" ,home_about_path,class:"nav-link"%>
        </li>
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "My Friends" ,friend_recs_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Add Friend" ,new_friend_rec_path,class:"nav-link"%>
          </li>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out" ,destroy_user_session_path,method: :delete,class:"nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Edit Profile" , edit_user_registration_path,class:"nav-link"%>
          </li>
        <% else%>
          <li class="nav-item">
          <%= link_to "Sign Up" ,new_user_registration_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to "Sign In" ,new_user_session_path,class:"nav-link"%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2>Stores your friends details</h2>
<br>
<p>You just have to create your own account in this app and you can go on saving your friends details</p>
<br>
<p>No one can see your friends details without your sign in credentials</p>

app/views/home/index.html.erb
<h1></h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render  'home/header'%>
    </div>  
    <div class="container">
    <% if notice %>
      <%= render 'layouts/alert'%>
    <%end%>
      <br/>
      <%= yield %>
    </div>
    <div class="container-fluid-success">
      <%= render 'home/footer'%>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>